version: '2'
services:

  postgres:
    image: postgres
    container_name: postgres_texts

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - ~/HomeProjects/data/textformatter:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
